# -*- coding: utf-8 -*-
"""SUMMARisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YU25MVvOb33YUHDYZg7bJR91an3aWni
"""

import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation
from heapq import nlargest

from transformers import pipeline

model = pipeline("summarization", model="facebook/bart-large-cnn")

text="It was late at night that I was returning home from work. For the past few days I had been working overtime which was the cause of me returning late. While I was normally cruising down a block playing my favourite music, the radio suddenly began to cause static. The music stopped and within a few minutes my car engine stopped too. I was now in the middle of an unknown location. My gas tank seemed alright. I got out of the car to see what was wrong with my engine when I spotted a female figure in the distance. I couldn't see her face as it all seemed dark."

text=model(text)[0]["summary_text"]

stopwords=list( STOP_WORDS)
nlp = spacy.load("en_core_web_sm") # Load the English language model
doc = nlp(text)
word_freq = {}
for token in doc:
  if token.text.lower() not in stopwords and token.text.lower() not in punctuation:
    if token.text not in word_freq.keys():
      word_freq[token.text]=1
    else :
        word_freq[token.text]+=1

max_freq=max(word_freq.values())
# frequency generated
for word in word_freq.keys():
  word_freq[word]=word_freq[word]/max_freq

# print(word_freq)

sen_token=[sentence for sentence in doc.sents]
# print(sen_token)

sen_scores={}
for sent in sen_token:
  for word in sent:
    if word.text in word_freq:
      if sent not in sen_scores.keys():
        sen_scores[sent]=word_freq[word.text]
      else :
        sen_scores[sent]+=word_freq[word.text]
# print(sen_scores)

select_len=int(len(sen_scores)*0.4)
if select_len<2:
  select_len=2
print(select_len)

summary=nlargest(select_len,sen_scores, key=sen_scores.get)
final_summary=[word.text for word in summary]

summary=" ".join( final_summary)
text

